export { api, appApi, MOCKS_ENABLED } from './client'
export { useApi } from './use-api'
export { ApiError } from './transport'
export type { HttpMethod, Query, RequestOptions } from './transport'
export { onAuthFailure } from './auth-bridge'
export { onReachability } from './connection-bridge'
export { registerMock, setMockOffline, type MockHandler, type MockContext } from './mock'
export type { Result, ListOpts } from './types'
export { resultMessage, resultError, errorMessage } from './types'
